{"name": "Проверка ошибки при создания пользователя с уже существующим логином", "status": "passed", "start": 1718885322306, "stop": 1718885322690, "uuid": "599c1460-5088-4d59-b612-947e5577ad66", "historyId": "e3ebd9fd6fb4ee11d2ff66010caacc39", "testCaseId": "e3ebd9fd6fb4ee11d2ff66010caacc39", "fullName": "tests.test_user_registration.TestUserRegistration#test_user_registration_double_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_registration"}, {"name": "subSuite", "value": "TestUserRegistration"}, {"name": "host", "value": "DESKTOP-9ENBRFN"}, {"name": "thread", "value": "2608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_registration"}]}